export { default as About } from './About'
export { default as Resume } from './Resume'
export { default as Works } from './Works'
export { default as Blogs } from './Blogs'
export { default as Contact } from './Contact'